/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as CanaryRouteImport } from './routes/canary'
import { Route as ControlProfileRouteImport } from './routes/control-profile'
import { Route as DriftRouteImport } from './routes/drift'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LkgRouteImport } from './routes/lkg'
import { Route as ResponseRouteImport } from './routes/response'
import { Route as SafetyRouteImport } from './routes/safety'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CanaryRoute = CanaryRouteImport.update({
  id: '/canary',
  path: '/canary',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlProfileRoute = ControlProfileRouteImport.update({
  id: '/control-profile',
  path: '/control-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DriftRoute = DriftRouteImport.update({
  id: '/drift',
  path: '/drift',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LkgRoute = LkgRouteImport.update({
  id: '/lkg',
  path: '/lkg',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponseRoute = ResponseRouteImport.update({
  id: '/response',
  path: '/response',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/canary': typeof CanaryRoute
  '/control-profile': typeof ControlProfileRoute
  '/drift': typeof DriftRoute
  '/health': typeof HealthRoute
  '/lkg': typeof LkgRoute
  '/response': typeof ResponseRoute
  '/safety': typeof SafetyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/canary': typeof CanaryRoute
  '/control-profile': typeof ControlProfileRoute
  '/drift': typeof DriftRoute
  '/health': typeof HealthRoute
  '/lkg': typeof LkgRoute
  '/response': typeof ResponseRoute
  '/safety': typeof SafetyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/canary': typeof CanaryRoute
  '/control-profile': typeof ControlProfileRoute
  '/drift': typeof DriftRoute
  '/health': typeof HealthRoute
  '/lkg': typeof LkgRoute
  '/response': typeof ResponseRoute
  '/safety': typeof SafetyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/canary'
    | '/control-profile'
    | '/drift'
    | '/health'
    | '/lkg'
    | '/response'
    | '/safety'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/canary'
    | '/control-profile'
    | '/drift'
    | '/health'
    | '/lkg'
    | '/response'
    | '/safety'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/canary'
    | '/control-profile'
    | '/drift'
    | '/health'
    | '/lkg'
    | '/response'
    | '/safety'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  CanaryRoute: typeof CanaryRoute
  ControlProfileRoute: typeof ControlProfileRoute
  DriftRoute: typeof DriftRoute
  HealthRoute: typeof HealthRoute
  LkgRoute: typeof LkgRoute
  ResponseRoute: typeof ResponseRoute
  SafetyRoute: typeof SafetyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canary': {
      id: '/canary'
      path: '/canary'
      fullPath: '/canary'
      preLoaderRoute: typeof CanaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-profile': {
      id: '/control-profile'
      path: '/control-profile'
      fullPath: '/control-profile'
      preLoaderRoute: typeof ControlProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drift': {
      id: '/drift'
      path: '/drift'
      fullPath: '/drift'
      preLoaderRoute: typeof DriftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lkg': {
      id: '/lkg'
      path: '/lkg'
      fullPath: '/lkg'
      preLoaderRoute: typeof LkgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/response': {
      id: '/response'
      path: '/response'
      fullPath: '/response'
      preLoaderRoute: typeof ResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  CanaryRoute: CanaryRoute,
  ControlProfileRoute: ControlProfileRoute,
  DriftRoute: DriftRoute,
  HealthRoute: HealthRoute,
  LkgRoute: LkgRoute,
  ResponseRoute: ResponseRoute,
  SafetyRoute: SafetyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
